//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazyn3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienia()
        {
            this.Towary = new HashSet<Towary>();
        }
    
        public int IdZamowienia { get; set; }
        public string adres { get; set; }
        public string NumerZamowienia { get; set; }
        public string AspNetUsersId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Towary> Towary { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
